language: python
os: linux
python:
  - "3.8"
# command to install dependencies
script:
  - pytest tests/test.py
#  - python -m black . --check --line-length=99
#  - python -m flake8 --exclude=migrations --max-line-length=99
install:
  - pip install -r requirements.txt

after_success:
  - python -m coveralls

deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESS_KEY_ID
  secret_access_key: $SECRET_ACCESS_KEY
  region: "us-west-2"
  app: "polls-app"
  env: "polls-app-integration"
  bucket_name: "elasticbeanstalk-us-west-2-698845801092"
  on:
    branch: main