#language: python
#python:
#  - "3.11"
## command to install dependencies
#install:
#  - pip install -r requirements.txt
#deploy:
#  provider: elasticbeanstalk
#  access_key_id: $ACCESS_KEY_ID
#  secret_access_key: $SECRET_ACCESS_KEY
#  region: "us-west-2"
#  app: "polls"