language: python
python:
  - "3.11"
# command to install dependencies
script:
  - pytest tests/test.py
install:
  - pip install -r requirements.txt
deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESS_KEY_ID
  secret_access_key: $SECRET_ACCESS_KEY
  region: "us-west-2"
  app: "polls-app"
  env: "polls-app-integration"
  bucket_name: "elasticbeanstalk-us-west-2-698845801092"
  on:
    branch: master